#############################  Ecomm  Service   #######################################
###Register Users
POST http://localhost:4004/odata/v4/ecommservice/Users
Content-Type: application/json

{ "ID": "58040e66-1dcd-4ffb-ab10-fdce32028b80",
  "username": "Chandan",
  "email": "chandan@sap.com",
  "password": "123",
  "isAdmin": true
  }

### Run login action
POST http://localhost:4004/odata/v4/ecommservice/login
Content-Type: application/json

{ "email": "chandan@sap.com",
  "password": "123"
  }

### Read Products
GET http://localhost:4004/odata/v4/ecommservice/Products


############################# Admin  Service   #######################################
###Get Users using basic Auth
# GET http://localhost:4004/odata/v4/ecomm-admin/Users
# Authorization: Basic 58040e66-1dcd-4ffb-ab10-fdce32028b79:123

###Get Users
GET http://localhost:4004/odata/v4/ecomm-admin/Users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjU4MDQwZTY2LTFkY2QtNGZmYi1hYjEwLWZkY2UzMjAyOGI4MCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcwNTkxNjg4NSwiZXhwIjoxNzA2MDAzMjg1fQ.sYEnFeAi0E8g6oNce9ZVrr4ZMIim98zav3mI8MJ_bLg

### Run Update on Users entiry (Admin can not update User password because that is a hidden field in Admin service)
PATCH http://localhost:4004/odata/v4/ecomm-admin/Users(58040e66-1dcd-4ffb-ab10-fdce32028b80)
Content-Type: application/json

{ "username": "Chandan",
  "isAdmin": true
  }

### Create Product
POST http://localhost:4004/odata/v4/ecomm-admin/Products
Content-Type: application/json

{   "title": "Electronics",
    "desc": "Dell Monitor2",
    "img": "test img",
    "categories": [ "Electronics2" , "Monitor2" ],
    "size": "36 Inch",
    "color": "Black",
    "price": 30.5,
    "currency_code": "INR"
  } 

### Get Products
GET http://localhost:4004/odata/v4/ecomm-admin/Products

### Get Orders
GET http://localhost:4004/odata/v4/ecomm-admin/Orders

### Get Carts
GET http://localhost:4004/odata/v4/ecomm-admin/Carts

### Get Products by categories(Odata Lambda operator)  ----Not working
GET http://localhost:4004/odata/v4/ecomm-admin/Products?$filter=categories/any(s:contains(s, 'Electro'))

### Test  ----Not working
GET http://localhost:4004/odata/v4/ecomm-admin/Products?$filter=price eq 30.5

### Get Top 5 products by createdAt
GET http://localhost:4004/odata/v4/ecomm-admin/Products?$orderby=createdAt desc&$top=2



############################# Users Service   #######################################
### Run Update on Users entiry
PATCH http://localhost:4004/odata/v4/ecomm-user/Users(58040e66-1dcd-4ffb-ab10-fdce32028b79)
Content-Type: application/json

{ "username": "Abhishek",
  "password": "1234"
  }

### Create Cart
POST http://localhost:4004/odata/v4/ecomm-user/Carts
Content-Type: application/json

{   "userId_ID": "58040e66-1dcd-4ffb-ab10-fdce32028b80",
    "products": [
      {
        "productId_ID" : "1f341757-e7c9-4091-adf2-94bb681370d1",
         "quantity" : 2
      }
    ]
  } 

### Get Carts
GET http://localhost:4004/odata/v4/ecomm-user/Carts?$expand=products

### Create Order
POST http://localhost:4004/odata/v4/ecomm-user/Orders
Content-Type: application/json

{   "userId_ID": "58040e66-1dcd-4ffb-ab10-fdce32028b80",
    "products": [
      {
        "productId_ID" : "1f341757-e7c9-4091-adf2-94bb681370d1",
         "quantity" : 2
      }
    ],
    "amount" : 20.2,
    "address_Country" : "India",
    "status" : "Pending"
  } 

### Update Order
PUT http://localhost:4004/odata/v4/ecomm-user/Orders(19b1f2b7-5039-4e5d-bfc8-9cb3de23fa5c)
Content-Type: application/json

{   "userId_ID": "58040e66-1dcd-4ffb-ab10-fdce32028b80",
    "products": [
      {
        "productId_ID" : "1f341757-e7c9-4091-adf2-94bb681370d1",
         "quantity" : 2
      }
    ],
    "amount" : 20.5,
    "address_Country" : "India",
    "status" : "Pending"
  }  

### Get Orders
GET http://localhost:4004/odata/v4/ecomm-user/Orders

### Get User
GET http://localhost:4004/odata/v4/ecomm-user/Users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjU4MDQwZTY2LTFkY2QtNGZmYi1hYjEwLWZkY2UzMjAyOGI4MSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDU5MTY5MDMsImV4cCI6MTcwNjAwMzMwM30.pZuhak_nzaAtUIZqD3HlsO2xsnIoDps2hPhGc_nJcs0